Workaround for IntelliJ not pulling sfm-util with correct classifier, close #3787
Motivation:

```
java.lang.UnsupportedClassVersionError: org/simpleflatmapper/util/ParallelReader has been
compiled by a more recent version of the Java Runtime (class file version 53.0),
this version of the Java Runtime only recognizes class file versions up to 52.0
```

We pull `org.simpleflatmapper:lightning-csv:7.0.3` with no classifier as we want to be compatible with JDK8.

Sadly, IntelliJ messes up with transitive dependency management and pulls `org.simpleflatmapper:sfm-util:7.0.3:jdk9` instead of `org.simpleflatmapper:sfm-util:7.0.3`.
This happens probably because IntelliJ resolves dependency based on the JDK it uses to run instead of the one configured for the module.

The issue doesn't happen when launching from command line, eg maven. It only happens when launch from IntelliJ with the `Engine` main class.

Modification:

The workaround is for us to exclude `sfm-util` from `lightning-csv` dependencies and explicitly pull it without classifier.

Result:

sfm for JDK8 works properly when launched from IntelliJ.