Fix currentLocationRegex in Java DSL, close #4187
Motivation:

j.l.ClassCastException: class io.gatling.http.response.Response cannot be cast to class java.lang.String

Modification:

Fix check type that was assigned by mistake to HeaderRegex instead of CurrentLocationRegex